
"use client"

import { useState, useMemo } from "react"
import { AppShell } from "@/components/layout/app-shell"
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import { 
  FileText, 
  Download, 
  Plus, 
  Search,
  BrainCircuit,
  Wrench,
  Loader2,
  Calendar,
  Building2,
  Monitor,
  Mail,
  ChevronRight,
  ArrowLeft,
  Save,
  FileCheck
} from "lucide-react"
import { useFirestore, useCollection, useMemoFirebase, useUser, useDoc } from "@/firebase"
import { collection, doc, query, where, serverTimestamp, orderBy, limit } from "firebase/firestore"
import { addDocumentNonBlocking } from "@/firebase/non-blocking-updates"
import { Badge } from "@/components/ui/badge"
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { useToast } from "@/hooks/use-toast"

export default function ReportsPage() {
  const db = useFirestore()
  const { user: currentUser } = useUser()
  const { toast } = useToast()

  // State Management
  const [step, setStep] = useState<1 | 2 | 3 | 4>(1)
  const [reportScope, setReportScope] = useState<"GENERAL" | "DEPARTMENT" | null>(null)
  const [selectedDeptId, setSelectedDeptId] = useState<string | null>(null)
  const [selectedEqId, setSelectedEqId] = useState<string | null>(null)
  const [isGenerating, setIsGenerating] = useState(false)
  const [isSaving, setIsSaving] = useState(false)

  // Recipient info for Email
  const [recipientEmail, setRecipientEmail] = useState("")

  // Data Fetching
  const departmentsQuery = useMemoFirebase(() => {
    if (!db) return null
    return collection(db, "departments")
  }, [db])
  const { data: departments, isLoading: isDeptsLoading } = useCollection(departmentsQuery)

  const equipmentQuery = useMemoFirebase(() => {
    if (!db || !selectedDeptId) return null
    return query(collection(db, "equipment"), where("departmentId", "==", selectedDeptId))
  }, [db, selectedDeptId])
  const { data: equipment, isLoading: isEqLoading } = useCollection(equipmentQuery)

  // Fetch latest AI session for selected equipment
  const aiSessionsQuery = useMemoFirebase(() => {
    if (!db || !selectedEqId) return null
    return query(
      collection(db, "equipment", selectedEqId, "aiTroubleshootingSessions"),
      orderBy("createdAt", "desc"),
      limit(1)
    )
  }, [db, selectedEqId])
  const { data: latestAiSessions } = useCollection(aiSessionsQuery)
  const latestAiSession = latestAiSessions?.[0]

  const selectedDept = departments?.find(d => d.id === selectedDeptId)
  const selectedEq = equipment?.find(e => e.id === selectedEqId)

  const handleDownloadWord = () => {
    if (!selectedEq) return
    
    const content = `
      BIOMEDLINK TECHNICAL REPORT
      ===========================
      Asset: ${selectedEq.name}
      Serial Number: ${selectedEq.serialNumber}
      Manufacturer: ${selectedEq.manufacturer}
      Department: ${selectedDept?.name || 'N/A'}
      Report Date: ${new Date().toLocaleDateString()}

      DIAGNOSTIC SUMMARY:
      ${latestAiSession?.resolutionSummary || 'No recent AI troubleshooting sessions found.'}

      TECHNICAL NOTES:
      - System status: ${selectedEq.status}
      - Last Service: ${selectedEq.lastServiceDate || 'N/A'}
      - Generated by BioMedLink Core Terminal.
    `
    
    const blob = new Blob([content], { type: "application/msword" })
    const url = URL.createObjectURL(blob)
    const link = document.createElement("a")
    link.href = url
    link.download = `Report_${selectedEq.serialNumber}.doc`
    document.body.appendChild(link)
    link.click()
    document.body.removeChild(link)
    toast({ title: "Word Doc Generated", description: "Report exported successfully." })
  }

  const handleEmailOutlook = () => {
    if (!selectedEq) return
    const subject = encodeURIComponent(`BioMedLink Report: ${selectedEq.name} (${selectedEq.serialNumber})`)
    const body = encodeURIComponent(`
Dear Team,

Please find the technical report for the following asset:
Asset: ${selectedEq.name}
S/N: ${selectedEq.serialNumber}
Status: ${selectedEq.status}

Diagnosis: ${latestAiSession?.resolutionSummary || 'Pending'}

Best regards,
${currentUser?.email}
    `)
    window.location.href = `mailto:${recipientEmail}?subject=${subject}&body=${body}`
    toast({ title: "Opening Mail Client", description: "Outlook/Mail protocol initiated." })
  }

  const handleSaveReport = () => {
    if (!db || !selectedEq) return
    setIsSaving(true)
    
    const reportData = {
      equipmentId: selectedEq.id,
      engineerId: currentUser?.uid,
      type: "COMPLIANCE_AUDIT",
      aiSessionId: latestAiSession?.id || null,
      content: latestAiSession?.resolutionSummary || "Standard Audit",
      createdAt: serverTimestamp()
    }

    addDocumentNonBlocking(collection(db, "reports"), reportData)
    
    setTimeout(() => {
      setIsSaving(false)
      toast({ title: "Report Archived", description: "Document saved to hospital registry." })
      setStep(1)
      setSelectedDeptId(null)
      setSelectedEqId(null)
    }, 1000)
  }

  return (
    <AppShell>
      <div className="max-w-5xl mx-auto space-y-8">
        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
          <div>
            <h1 className="text-3xl font-headline font-bold text-primary flex items-center gap-3">
              <FileText className="w-8 h-8 text-primary" />
              Compliance Registry
            </h1>
            <p className="text-muted-foreground mt-1">Generate ISO-certified hardware audit and maintenance compliance documents.</p>
          </div>
          {step > 1 && (
            <Button variant="ghost" onClick={() => setStep((s) => (s - 1) as any)} className="gap-2">
              <ArrowLeft className="w-4 h-4" />
              Back
            </Button>
          )}
        </div>

        {/* Step 1: Scope */}
        {step === 1 && (
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            <Card 
              className="border-none shadow-sm hover:ring-2 hover:ring-primary transition-all cursor-pointer group p-6"
              onClick={() => { setReportScope("GENERAL"); setStep(4); }}
            >
              <div className="w-12 h-12 rounded-xl bg-primary/10 flex items-center justify-center mb-4 group-hover:bg-primary group-hover:text-white transition-colors">
                <FileCheck className="w-6 h-6" />
              </div>
              <h3 className="text-xl font-bold">General Hospital Audit</h3>
              <p className="text-sm text-muted-foreground mt-2">Generate a global report covering all assets, downtime trends, and compliance status across the facility.</p>
            </Card>

            <Card 
              className="border-none shadow-sm hover:ring-2 hover:ring-primary transition-all cursor-pointer group p-6"
              onClick={() => { setReportScope("DEPARTMENT"); setStep(2); }}
            >
              <div className="w-12 h-12 rounded-xl bg-accent/10 flex items-center justify-center mb-4 group-hover:bg-accent group-hover:text-white transition-colors">
                <Building2 className="w-6 h-6" />
              </div>
              <h3 className="text-xl font-bold">Departmental / Asset Report</h3>
              <p className="text-sm text-muted-foreground mt-2">Target specific sectors or individual clinical hardware for deep-dive technical diagnostics.</p>
            </Card>
          </div>
        )}

        {/* Step 2: Department Selection */}
        {step === 2 && (
          <div className="space-y-4">
            <h2 className="text-xl font-bold">Select Hospital Department</h2>
            <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4">
              {isDeptsLoading ? (
                <div className="col-span-full py-10 flex justify-center"><Loader2 className="w-8 h-8 animate-spin text-primary" /></div>
              ) : departments?.map(dept => (
                <Card 
                  key={dept.id} 
                  className="border-none shadow-sm hover:ring-2 hover:ring-primary transition-all cursor-pointer p-4 flex items-center justify-between"
                  onClick={() => { setSelectedDeptId(dept.id); setStep(3); }}
                >
                  <div className="flex items-center gap-3">
                    <Building2 className="w-5 h-5 text-muted-foreground" />
                    <span className="font-semibold">{dept.name}</span>
                  </div>
                  <ChevronRight className="w-4 h-4 text-muted-foreground" />
                </Card>
              ))}
            </div>
          </div>
        )}

        {/* Step 3: Equipment Selection */}
        {step === 3 && (
          <div className="space-y-4">
            <div className="flex items-center gap-2 text-xs font-bold text-primary uppercase tracking-widest">
              <Building2 className="w-3 h-3" />
              Sector: {selectedDept?.name}
            </div>
            <h2 className="text-xl font-bold">Select Target Asset</h2>
            <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4">
              {isEqLoading ? (
                <div className="col-span-full py-10 flex justify-center"><Loader2 className="w-8 h-8 animate-spin text-primary" /></div>
              ) : equipment?.map(eq => (
                <Card 
                  key={eq.id} 
                  className="border-none shadow-sm hover:ring-2 hover:ring-primary transition-all cursor-pointer p-4 flex items-center justify-between"
                  onClick={() => { setSelectedEqId(eq.id); setStep(4); }}
                >
                  <div className="flex items-center gap-3">
                    <Monitor className="w-5 h-5 text-muted-foreground" />
                    <div className="flex flex-col">
                      <span className="font-semibold text-sm">{eq.name}</span>
                      <span className="text-[10px] text-muted-foreground font-mono">{eq.serialNumber}</span>
                    </div>
                  </div>
                  <ChevronRight className="w-4 h-4 text-muted-foreground" />
                </Card>
              ))}
            </div>
          </div>
        )}

        {/* Step 4: Report Actions */}
        {step === 4 && (
          <div className="grid grid-cols-1 lg:grid-cols-12 gap-8">
            <div className="lg:col-span-7 space-y-6">
              <Card className="border-none shadow-lg overflow-hidden">
                <div className="h-2 bg-primary" />
                <CardHeader>
                  <div className="flex items-center justify-between">
                    <Badge variant="outline" className="text-primary border-primary">Technical Protocol</Badge>
                    <span className="text-xs text-muted-foreground font-mono">{new Date().toLocaleDateString()}</span>
                  </div>
                  <CardTitle className="text-2xl mt-4">
                    {reportScope === "GENERAL" ? "Facility-Wide Compliance Audit" : `Asset Report: ${selectedEq?.name}`}
                  </CardTitle>
                  <CardDescription>
                    {reportScope === "GENERAL" 
                      ? "Global overview of all registered departments and active assets."
                      : `Detailed technical profile for S/N: ${selectedEq?.serialNumber} located in ${selectedDept?.name}.`
                    }
                  </CardDescription>
                </CardHeader>
                <CardContent className="space-y-6">
                  {selectedEq && latestAiSession && (
                    <div className="p-4 bg-accent/5 border border-accent/20 rounded-xl space-y-3">
                      <div className="flex items-center gap-2 text-accent">
                        <BrainCircuit className="w-5 h-5" />
                        <h4 className="font-bold text-sm">AI Troubleshooting Found</h4>
                      </div>
                      <p className="text-sm text-muted-foreground leading-relaxed italic">
                        "{latestAiSession.resolutionSummary}"
                      </p>
                      <p className="text-[10px] text-muted-foreground uppercase font-bold">Latest session: {latestAiSession.createdAt?.toDate ? latestAiSession.createdAt.toDate().toLocaleDateString() : 'Just now'}</p>
                    </div>
                  )}

                  <div className="space-y-4">
                    <Label className="text-xs font-bold uppercase text-muted-foreground">Internal Routing (Email Receiver)</Label>
                    <div className="relative">
                      <Mail className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-muted-foreground" />
                      <Input 
                        placeholder="recipient@hospital.admin" 
                        className="pl-10 h-11"
                        value={recipientEmail}
                        onChange={(e) => setRecipientEmail(e.target.value)}
                      />
                    </div>
                  </div>

                  <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 pt-6 border-t">
                    <Button 
                      variant="outline" 
                      className="h-12 font-bold gap-2"
                      onClick={handleDownloadWord}
                    >
                      <Download className="w-4 h-4" />
                      Download Word Doc
                    </Button>
                    <Button 
                      className="h-12 font-bold gap-2 shadow-lg shadow-primary/20"
                      disabled={isSaving}
                      onClick={handleSaveReport}
                    >
                      {isSaving ? <Loader2 className="w-4 h-4 animate-spin" /> : <Save className="w-4 h-4" />}
                      Save to Registry
                    </Button>
                    <Button 
                      variant="secondary" 
                      className="h-12 font-bold gap-2 sm:col-span-2"
                      onClick={handleEmailOutlook}
                    >
                      <Mail className="w-4 h-4" />
                      Send via Outlook
                    </Button>
                  </div>
                </CardContent>
              </Card>
            </div>

            <div className="lg:col-span-5 space-y-4">
              <h3 className="font-bold text-sm uppercase tracking-widest text-muted-foreground px-2">Compliance History</h3>
              <div className="space-y-3">
                <Card className="border-none shadow-sm p-4 flex gap-4 items-start bg-muted/30">
                  <div className="w-10 h-10 rounded-lg bg-background flex items-center justify-center border shrink-0">
                    <FileCheck className="w-5 h-5 text-primary" />
                  </div>
                  <div>
                    <h4 className="font-bold text-sm">ISO Audit 2024.1</h4>
                    <p className="text-xs text-muted-foreground">Generated by System Core. Status: Verified.</p>
                  </div>
                </Card>
                <Card className="border-none shadow-sm p-4 flex gap-4 items-start bg-muted/30 opacity-50">
                  <div className="w-10 h-10 rounded-lg bg-background flex items-center justify-center border shrink-0">
                    <Wrench className="w-5 h-5 text-muted-foreground" />
                  </div>
                  <div>
                    <h4 className="font-bold text-sm">Preventive Log Archive</h4>
                    <p className="text-xs text-muted-foreground">System backup scheduled for midnight.</p>
                  </div>
                </Card>
              </div>
            </div>
          </div>
        )}
      </div>
    </AppShell>
  )
}
