
"use client"

import { useState, useMemo, useEffect } from "react"
import { AppShell } from "@/components/layout/app-shell"
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import { 
  FileText, 
  Download, 
  Search,
  BrainCircuit,
  Wrench,
  Loader2,
  Calendar,
  Building2,
  Monitor,
  Mail,
  ChevronRight,
  ArrowLeft,
  Save,
  FileCheck,
  Type,
  Users,
  Globe
} from "lucide-react"
import { useFirestore, useCollection, useMemoFirebase, useUser, useDoc } from "@/firebase"
import { collection, doc, query, where, serverTimestamp, orderBy, limit } from "firebase/firestore"
import { addDocumentNonBlocking } from "@/firebase/non-blocking-updates"
import { Badge } from "@/components/ui/badge"
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Textarea } from "@/components/ui/textarea"
import { useToast } from "@/hooks/use-toast"

export default function ReportsPage() {
  const db = useFirestore()
  const { user: currentUser } = useUser()
  const { toast } = useToast()

  // State Management
  const [step, setStep] = useState<1 | 2 | 3 | 4>(1)
  const [reportScope, setReportScope] = useState<"GENERAL" | "DEPARTMENT" | null>(null)
  const [selectedDeptId, setSelectedDeptId] = useState<string | null>(null)
  const [selectedEqId, setSelectedEqId] = useState<string | null>(null)
  const [isSaving, setIsSaving] = useState(false)

  // Email/Report Content State
  const [recipientEmail, setRecipientEmail] = useState("")
  const [recipientCc, setRecipientCc] = useState("")
  const [recipientBcc, setRecipientBcc] = useState("")
  const [editableContent, setEditableContent] = useState("")

  // Data Fetching
  const departmentsQuery = useMemoFirebase(() => {
    if (!db) return null
    return collection(db, "departments")
  }, [db])
  const { data: departments, isLoading: isDeptsLoading } = useCollection(departmentsQuery)

  const equipmentQuery = useMemoFirebase(() => {
    if (!db || !selectedDeptId) return null
    return query(collection(db, "equipment"), where("departmentId", "==", selectedDeptId))
  }, [db, selectedDeptId])
  const { data: equipment, isLoading: isEqLoading } = useCollection(equipmentQuery)

  // Fetch latest AI session for selected equipment
  const aiSessionsQuery = useMemoFirebase(() => {
    if (!db || !selectedEqId) return null
    return query(
      collection(db, "equipment", selectedEqId, "aiTroubleshootingSessions"),
      orderBy("createdAt", "desc"),
      limit(1)
    )
  }, [db, selectedEqId])
  const { data: latestAiSessions } = useCollection(aiSessionsQuery)
  const latestAiSession = latestAiSessions?.[0]

  const selectedDept = departments?.find(d => d.id === selectedDeptId)
  const selectedEq = equipment?.find(e => e.id === selectedEqId)

  // Auto-populate editable content when reaching Step 4
  useEffect(() => {
    if (step === 4) {
      let content = ""
      const dateStr = new Date().toLocaleDateString()
      
      if (reportScope === "GENERAL") {
        content = `BIOMEDLINK GENERAL FACILITY AUDIT\n` +
                  `================================\n` +
                  `Report Date: ${dateStr}\n` +
                  `Generated By: ${currentUser?.email}\n\n` +
                  `SUMMARY:\n` +
                  `Global overview of hospital clinical hardware compliance. All departments verified according to standard protocol.`
      } else if (selectedEq) {
        content = `BIOMEDLINK TECHNICAL REPORT\n` +
                  `===========================\n` +
                  `Asset: ${selectedEq.name}\n` +
                  `S/N: ${selectedEq.serialNumber}\n` +
                  `Manufacturer: ${selectedEq.manufacturer}\n` +
                  `Department: ${selectedDept?.name || 'N/A'}\n` +
                  `Report Date: ${dateStr}\n\n` +
                  `DIAGNOSTIC SUMMARY:\n` +
                  `${latestAiSession?.resolutionSummary || 'No recent AI troubleshooting sessions found for this asset.'}\n\n` +
                  `TECHNICAL NOTES:\n` +
                  `- System status: ${selectedEq.status}\n` +
                  `- Last Service: ${selectedEq.lastServiceDate || 'Not Logged'}\n` +
                  `- Next Service Scheduled: ${selectedEq.nextServiceDate || 'Pending'}\n\n` +
                  `Generated via BioMedLink Core Intelligence Terminal.`
      }
      setEditableContent(content)
    }
  }, [step, reportScope, selectedEq, latestAiSession, selectedDept, currentUser])

  const handleDownloadWord = () => {
    if (!editableContent) return
    
    const blob = new Blob([editableContent], { type: "application/msword" })
    const url = URL.createObjectURL(blob)
    const link = document.createElement("a")
    link.href = url
    link.download = reportScope === "GENERAL" ? "General_Audit.doc" : `Report_${selectedEq?.serialNumber}.doc`
    document.body.appendChild(link)
    link.click()
    document.body.removeChild(link)
    toast({ title: "Word Doc Generated", description: "Your custom technical report has been exported." })
  }

  const getEmailMetadata = () => {
    const subject = reportScope === "GENERAL" ? "BioMedLink: General Hospital Audit" : `BioMedLink Report: ${selectedEq?.name} (${selectedEq?.serialNumber})`
    return {
      subject: encodeURIComponent(subject),
      body: encodeURIComponent(editableContent)
    }
  }

  const handleEmailOutlook = () => {
    if (!editableContent) return
    const { subject, body } = getEmailMetadata()
    const mailtoUrl = `mailto:${recipientEmail}?cc=${recipientCc}&bcc=${recipientBcc}&subject=${subject}&body=${body}`
    window.location.href = mailtoUrl
    toast({ title: "Outlook Protocol Initiated", description: "Opening mail client with synchronized content." })
  }

  const handleEmailGmail = () => {
    if (!editableContent) return
    const { subject, body } = getEmailMetadata()
    const gmailUrl = `https://mail.google.com/mail/?view=cm&fs=1&to=${recipientEmail}&cc=${recipientCc}&bcc=${recipientBcc}&su=${subject}&body=${body}`
    window.open(gmailUrl, '_blank')
    toast({ title: "Gmail Protocol Initiated", description: "Opening Gmail composer in new tab." })
  }

  const handleSaveReport = () => {
    if (!db || !editableContent) return
    setIsSaving(true)
    
    const reportData = {
      equipmentId: selectedEq?.id || "FACILITY_WIDE",
      engineerId: currentUser?.uid,
      type: reportScope === "GENERAL" ? "FACILITY_AUDIT" : "ASSET_AUDIT",
      content: editableContent,
      createdAt: serverTimestamp()
    }

    addDocumentNonBlocking(collection(db, "reports"), reportData)
    
    setTimeout(() => {
      setIsSaving(false)
      toast({ title: "Archived to Registry", description: "This report has been permanently saved to the hospital's central audit database." })
      setStep(1)
      setSelectedDeptId(null)
      setSelectedEqId(null)
      setEditableContent("")
    }, 1000)
  }

  return (
    <AppShell>
      <div className="max-w-6xl mx-auto space-y-8">
        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
          <div>
            <h1 className="text-3xl font-headline font-bold text-primary flex items-center gap-3">
              <FileText className="w-8 h-8 text-primary" />
              Compliance Registry
            </h1>
            <p className="text-muted-foreground mt-1">Generate ISO-certified hardware audit and maintenance compliance documents.</p>
          </div>
          {step > 1 && (
            <Button variant="ghost" onClick={() => setStep((s) => (s - 1) as any)} className="gap-2">
              <ArrowLeft className="w-4 h-4" />
              Back
            </Button>
          )}
        </div>

        {/* Step 1: Scope Selection */}
        {step === 1 && (
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            <Card 
              className="border-none shadow-sm hover:ring-2 hover:ring-primary transition-all cursor-pointer group p-6"
              onClick={() => { setReportScope("GENERAL"); setStep(4); }}
            >
              <div className="w-12 h-12 rounded-xl bg-primary/10 flex items-center justify-center mb-4 group-hover:bg-primary group-hover:text-white transition-colors">
                <FileCheck className="w-6 h-6" />
              </div>
              <h3 className="text-xl font-bold">General Hospital Audit</h3>
              <p className="text-sm text-muted-foreground mt-2">Generate a global report covering all assets and compliance status across the facility.</p>
            </Card>

            <Card 
              className="border-none shadow-sm hover:ring-2 hover:ring-primary transition-all cursor-pointer group p-6"
              onClick={() => { setReportScope("DEPARTMENT"); setStep(2); }}
            >
              <div className="w-12 h-12 rounded-xl bg-accent/10 flex items-center justify-center mb-4 group-hover:bg-accent group-hover:text-white transition-colors">
                <Building2 className="w-6 h-6" />
              </div>
              <h3 className="text-xl font-bold">Departmental / Asset Report</h3>
              <p className="text-sm text-muted-foreground mt-2">Target specific sectors or individual clinical hardware for deep-dive technical diagnostics.</p>
            </Card>
          </div>
        )}

        {/* Step 2: Department Selection */}
        {step === 2 && (
          <div className="space-y-4">
            <h2 className="text-xl font-bold">Select Hospital Department</h2>
            <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4">
              {isDeptsLoading ? (
                <div className="col-span-full py-10 flex justify-center"><Loader2 className="w-8 h-8 animate-spin text-primary" /></div>
              ) : departments?.map(dept => (
                <Card 
                  key={dept.id} 
                  className="border-none shadow-sm hover:ring-2 hover:ring-primary transition-all cursor-pointer p-4 flex items-center justify-between"
                  onClick={() => { setSelectedDeptId(dept.id); setStep(3); }}
                >
                  <div className="flex items-center gap-3">
                    <Building2 className="w-5 h-5 text-muted-foreground" />
                    <span className="font-semibold">{dept.name}</span>
                  </div>
                  <ChevronRight className="w-4 h-4 text-muted-foreground" />
                </Card>
              ))}
            </div>
          </div>
        )}

        {/* Step 3: Equipment Selection */}
        {step === 3 && (
          <div className="space-y-4">
            <div className="flex items-center gap-2 text-xs font-bold text-primary uppercase tracking-widest">
              <Building2 className="w-3 h-3" />
              Sector: {selectedDept?.name}
            </div>
            <h2 className="text-xl font-bold">Select Target Asset</h2>
            <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4">
              {isEqLoading ? (
                <div className="col-span-full py-10 flex justify-center"><Loader2 className="w-8 h-8 animate-spin text-primary" /></div>
              ) : equipment?.map(eq => (
                <Card 
                  key={eq.id} 
                  className="border-none shadow-sm hover:ring-2 hover:ring-primary transition-all cursor-pointer p-4 flex items-center justify-between"
                  onClick={() => { setSelectedEqId(eq.id); setStep(4); }}
                >
                  <div className="flex items-center gap-3">
                    <Monitor className="w-5 h-5 text-muted-foreground" />
                    <div className="flex flex-col">
                      <span className="font-semibold text-sm">{eq.name}</span>
                      <span className="text-[10px] text-muted-foreground font-mono">{eq.serialNumber}</span>
                    </div>
                  </div>
                  <ChevronRight className="w-4 h-4 text-muted-foreground" />
                </Card>
              ))}
            </div>
          </div>
        )}

        {/* Step 4: Finalize & Edit Report */}
        {step === 4 && (
          <div className="grid grid-cols-1 lg:grid-cols-12 gap-8">
            {/* Editor Section */}
            <div className="lg:col-span-7 space-y-6">
              <Card className="border-none shadow-lg overflow-hidden">
                <div className="h-2 bg-primary" />
                <CardHeader className="bg-muted/10">
                  <div className="flex items-center justify-between">
                    <Badge variant="outline" className="text-primary border-primary">Technical Registry Protocol</Badge>
                    <span className="text-xs text-muted-foreground font-mono">{new Date().toLocaleDateString()}</span>
                  </div>
                  <CardTitle className="text-2xl mt-4">Edit Technical Document</CardTitle>
                  <CardDescription>Preview and refine technical details before generation.</CardDescription>
                </CardHeader>
                <CardContent className="p-6 space-y-6">
                  <div className="space-y-2">
                    <Label className="text-xs font-bold uppercase text-muted-foreground flex items-center gap-2">
                      <Type className="w-3 h-3" />
                      Report Content (Word & Email Body)
                    </Label>
                    <Textarea 
                      value={editableContent}
                      onChange={(e) => setEditableContent(e.target.value)}
                      className="min-h-[400px] font-mono text-sm leading-relaxed p-4 bg-background border-2"
                      placeholder="Type your technical summary here..."
                    />
                  </div>
                </CardContent>
              </Card>
            </div>

            {/* Config Section */}
            <div className="lg:col-span-5 space-y-6">
              <Card className="border-none shadow-sm">
                <CardHeader>
                  <CardTitle className="text-lg flex items-center gap-2">
                    <Users className="w-5 h-5 text-primary" />
                    Dispatch Protocol
                  </CardTitle>
                  <CardDescription>Configure stakeholders and delivery methods.</CardDescription>
                </CardHeader>
                <CardContent className="space-y-4">
                  <div className="space-y-2">
                    <Label className="text-[10px] font-bold uppercase text-muted-foreground">Primary Receiver (To)</Label>
                    <div className="relative">
                      <Mail className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-muted-foreground" />
                      <Input 
                        placeholder="admin@hospital.com" 
                        className="pl-10 h-11"
                        value={recipientEmail}
                        onChange={(e) => setRecipientEmail(e.target.value)}
                      />
                    </div>
                  </div>

                  <div className="grid grid-cols-2 gap-4">
                    <div className="space-y-2">
                      <Label className="text-[10px] font-bold uppercase text-muted-foreground">CC (Carbon Copy)</Label>
                      <Input 
                        placeholder="team@dept.com" 
                        className="h-11"
                        value={recipientCc}
                        onChange={(e) => setRecipientCc(e.target.value)}
                      />
                    </div>
                    <div className="space-y-2">
                      <Label className="text-[10px] font-bold uppercase text-muted-foreground">BCC (Blind Copy)</Label>
                      <Input 
                        placeholder="audit@compliance.org" 
                        className="h-11"
                        value={recipientBcc}
                        onChange={(e) => setRecipientBcc(e.target.value)}
                      />
                    </div>
                  </div>

                  <div className="pt-6 border-t space-y-3">
                    <Button 
                      className="w-full h-12 font-bold gap-2 shadow-lg shadow-primary/20"
                      disabled={isSaving}
                      onClick={handleSaveReport}
                    >
                      {isSaving ? <Loader2 className="w-4 h-4 animate-spin" /> : <Save className="w-4 h-4" />}
                      Archived to Registry
                    </Button>
                    
                    <div className="grid grid-cols-1 gap-3">
                      <Button 
                        variant="outline" 
                        className="w-full h-12 font-bold gap-2"
                        onClick={handleDownloadWord}
                      >
                        <Download className="w-4 h-4" />
                        Download Word Document
                      </Button>
                      
                      <div className="grid grid-cols-2 gap-3">
                        <Button 
                          variant="secondary" 
                          className="h-12 font-bold gap-2"
                          onClick={handleEmailOutlook}
                        >
                          <Mail className="w-4 h-4" />
                          Outlook
                        </Button>
                        <Button 
                          variant="secondary" 
                          className="h-12 font-bold gap-2"
                          onClick={handleEmailGmail}
                        >
                          <Globe className="w-4 h-4" />
                          Gmail
                        </Button>
                      </div>
                    </div>
                  </div>
                </CardContent>
              </Card>

              {/* Tips / Info */}
              <div className="p-4 bg-muted/30 rounded-xl border border-dashed text-center">
                <p className="text-[11px] text-muted-foreground leading-relaxed">
                  <strong>Technical Note:</strong> "Archived to Registry" saves the official document to the hospital's central Firestore database for long-term audit trail compliance.
                </p>
              </div>
            </div>
          </div>
        )}
      </div>
    </AppShell>
  )
}

    